# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15dd87db8ff4cb3ad8af1cb78fa3d74c3ee58d95fed2d5802848e2bc48932692ce7f115167d8d4e61dea33a58e3f3a997d03c35cce0f2cde9ab0b14e3d74b998

test:
  secret_key_base: 33d6f9193fcb88a2b646a154fcf060bc784a440d9e0515892d5b96929fd233da8495ef17f1bdd5dab14e404f74e379e85f52cbada5924b5ab6f4b719fec0d96c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
